"""initial schema: users, projects, prds (+ enable pgvector)

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-14

This is hand-written (not autogenerated) so it's easy to read and review. It:
  1. Enables the pgvector extension now, so the DB is ready for Phase 4 (RAG) with no
     future migration surprise. Neon and most managed Postgres support it out of the box.
  2. Creates the three Phase 1 tables with their foreign keys and constraints.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Enable pgvector (safe if already enabled). Needed for embeddings in Phase 4.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # 2. users
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    # 3. projects (owned by a user; deleting a user cascades to their projects)
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("target_audience", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_projects_owner_id", "projects", ["owner_id"])

    # 4. prds (one per project; content is the structured PRD as JSONB)
    op.create_table(
        "prds",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
    )
    # unique index enforces the 1-project-1-PRD rule at the DB level.
    op.create_index("ix_prds_project_id", "prds", ["project_id"], unique=True)


def downgrade() -> None:
    # Reverse order of creation so foreign keys don't block the drops.
    op.drop_index("ix_prds_project_id", table_name="prds")
    op.drop_table("prds")
    op.drop_index("ix_projects_owner_id", table_name="projects")
    op.drop_table("projects")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
    # We intentionally do NOT drop the vector extension on downgrade; other things may use it.
